#!/sbin/bb/busybox sh

BB=/sbin/bb/busybox

if [ -f /sbin/su ] && [ -f /system/app/*uper?ser.apk ]; then
	$BB echo "You have full working ROOT Installed!";
elif [ -f /sbin/su ] && [ -f /system/app/SuperSU.apk ]; then
	$BB echo "You have full working ROOT Installed!";
elif [ -f /sbin/su ] && [ -f /system/app/Superuser.apk ]; then
	$BB echo "You have full working ROOT Installed!";
elif [ -f /sbin/su ] && [ -f /data/app/Superuser.apk ]; then
	$BB echo "You have full working ROOT Installed!";
elif [ -f /sbin/su ] && [ -f /data/app/*uper?ser.apk ]; then
	$BB echo "You have full working ROOT Installed!";
elif [ -f /sbin/su ] && [ -f /data/app/Superuser.apk ]; then
	$BB echo "You have full working ROOT Installed!";
elif [ -x /sbin/su ] && [ -u /su/bin/su ]; then
	$BB echo "You have working ROOT Installed!!";
else
	$BB echo "You don't have ROOT installed!";
fi;
